version: '3.1'
services:
  peanutshell:
    image: ghcr.io/sugarforever/peanut-shell:latest
    pull_policy: always
    ports:
      - "8000:8000"
    volumes:
      - hf_data:/root/.cache

volumes:
  hf_data:
